name: Train and publish model

# This workflow is triggered manually. To run it, click the "Actions" tab on the repo page.
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Zip training data
        run: |
          zip -r data.zip data
      
      - name: Upload training data
        id: upload-training-data
        uses: sergeysova/jq-action@v2
        run: |
          RESPONSE=$(curl -X POST -H "Authorization: Token ${{ secrets.REPLICATE_API_TOKEN }}" https://dreambooth-api-experimental.replicate.com/v1/upload/data.zip)
          curl -X PUT -H "Content-Type: application/zip" --upload-file data.zip "$(jq -r ".upload_url" <<< "$RESPONSE")"
          echo "INSTANCE_DATA_URL=$(jq -r '.serving_url' <<< $RESPONSE)" >> $GITHUB_OUTPUT

      - name: Start training
        run: |
          curl -X POST \
          -H "Authorization: Token ${{ secrets.REPLICATE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                  "input": {
                      "instance_prompt": "a photo of a zzz person",
                      "class_prompt": "a photo of a person",
                      "instance_data": "${{ steps.upload-training-data.outputs.INSTANCE_DATA_URL }}",
                      "max_train_steps": 100 # TODO: set to 2000
                  },
                  "model": "zeke/zekebooth"
              }' \
          https://dreambooth-api-experimental.replicate.com/v1/trainings